name = "edgetunnel"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"            # KV绑定名默认不可修改
id = "bd3f4bf08b364a8f934cbfbaa02552f4"

[[routes]]
pattern = "lizi.zhaojianxiang.cc.cd"
custom_domain = true
